kind: pipeline
type: kubernetes
name: bookstack-docker

triggers:
  event:
  - cron
  cron:
  - nightly
  branch:
  - master

steps:
  - name: Build BookStack Docker image
    image: plugins/docker
    settings:
      repo: docker-registry.k8s.array21.dev/bookstack
      tags:
      - latest
      registry: docker-registry.k8s.array21.dev

  - name: Deploy to Kubernetes
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl set image deployment/bookstack bookstack=docker-registry.k8s.array21.dev/bookstack:latest
      
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: discord_webhook
      username: Drone CI/CD - BookStack Docker Image 
    when:
      status: [ failure ]
